Kms Cloud Web App/Models/Views/Layout/LayoutFriend.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;

namespace Kms.Cloud.WebApp.Models.Views {
    public class LayoutFriend {
        /// <summary>
        /// Información sobre la Región del Usuario
        /// </summary>
        public RegionInfo RegionInfo {
            get;
            set;
        }

        /// <summary>
        /// Información sobre la Cultura del Usuario
        /// </summary>
        public CultureInfo CultureInfo {
            get;
            set;
        }

        /// <summary>
        /// Nombre del Amigo
        /// </summary>
        public string Name {
            get;
            set;
        }

        /// <summary>
        /// Apellido del Amigo
        /// </summary>
        public string LastName {
            get;
            set;
        }

        /// <summary>
        /// URI de la fotografía del Amigo
        /// </summary>
        public Uri PictureUri {
            get;
            set;
        }

        /// <summary>
        /// Distancia Total recorrida por el Amigo (en cm)
        /// </summary>
        public double TotalDistanceCentimeters {
            get;
            set;
        }

        /// <summary>
        /// Distancia Total recorrida por el Amigo en las unidades de la región del Usuario
        /// </summary>
        public double TotalDistance {
            get {
                if ( this.RegionInfo.IsMetric )
                    return this.TotalDistanceCentimeters / 1000;
                else
                    return this.TotalDistanceCentimeters / 160934.4;
            }
        }

        /// <summary>
        /// Distancia Total recorrida por el Amigo en las unidades de la región del Usuario, en el formato de la Cultura del Usuario
        /// </summary>
        public string TotalDistanceString {
            get {
                return this.TotalDistance.ToString(
                    this.CultureInfo.NumberFormat
                );
            }
        }
    }
}

Kms Cloud Web App/Models/Views/Layout/LayoutNotification.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Kms.Cloud.WebApp.Models.Views {
    public class LayoutNotification {
        public Uri IconUri {
            get;
            set;
        }

        public string Title {
            get;
            set;
        }

        public string Description {
            get;
            set;
        }

        public bool Discarded {
            get;
            set;
        }
    }
}

Kms Cloud Web App/Models/Views/Layout/LayoutValues.cs
using Kms.Cloud.Database.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Globalization;

namespace Kms.Cloud.WebApp.Models.Views {    
    public class LayoutValues {
        public enum MainSection {
            MyProfile,
            Tips,
            Rewards,
            Friends
        }

        public LayoutValues() {
            this.UserPicture
                = new Uri("/Images/Header.DefaultUserIcon.png", UriKind.Relative);
        }

        public MainSection Section
            = MainSection.MyProfile;
        public int UnreadMessages
            = 0;

        /// <summary>
        /// Uri de la ubicación de la fotografía del Usuario
        /// </summary>
        public Uri UserPicture {
            get;
            set;
        }

        /// <summary>
        /// Nombre del Usuario
        /// </summary>
        public string UserName {
            get;
            set;
        }

        /// <summary>
        /// Apellido del Usuario
        /// </summary>
        public string UserLastname {
            get;
            set;
        }

        /// <summary>
        /// Un número arbitrario que evita que el browser genere caché para resultados
        /// en peticiones AJAX para alimentar las gráficas. Normalmente tiene un valor
        /// de la fecha del último registro en "Javascript Epoch".
        /// </summary>
        public Int64 AjaxCache { get; set; }

        /// <summary>
        /// Fecha de Creación de la Cuenta del Usuario, en milisegundos en Javascript Epoch.
        /// </summary>
        public Int64 UserSignup { get; set; }

        /// <summary>
        /// Distancia Total recorrida por el Usuario en las unidades de la región del Usuario
        /// </summary>
        public string TotalDistance {
            get {
                double totalDistance
                    = RegionInfo.CurrentRegion.IsMetric
                    ? this.TotalDistanceCentimeters.CentimetersToKilometers()
                    : this.TotalDistanceCentimeters.CentimetersToMiles();
                
                return totalDistance.ToLocalizedString();
            }
        }

        /// <summary>
        /// Distancia Total recorrida por el Usuario en Centímetros (establecer este valor, modifica el valor en <see cref="TotalDistance">TotalDistance</see>)
        /// </summary>
        public long TotalDistanceCentimeters {
            get;
            set;
        }

        /// <summary>
        /// Distancia Restante para liberar la próxima recompensa
        /// </summary>
        public string NextRewardsDistanceRemaining {
            get {
                double rewardDistanceSpan
                    = this.NextRewardDistanceCentimeters - this.TotalDistanceCentimeters;
                rewardDistanceSpan
                    = RegionInfo.CurrentRegion.IsMetric
                    ? rewardDistanceSpan.CentimetersToKilometers()
                    : rewardDistanceSpan.CentimetersToMiles();

                return ((long)rewardDistanceSpan).ToLocalizedString();
            }
        }

        /// <summary>
        /// Distancia en Millas en la cual se liberará la próxima recompensa
        /// </summary>
        public long NextRewardDistanceCentimeters {
            get;
            set;
        }

        /// <summary>
        /// Cadena que representa el lugar geográfico del usuario (País, Estado, Municipio)
        /// </summary>
        public string LocationString {
            get;
            set;
        }

        /// <summary>
        /// Cadena de Representación Compacta del GUID de la Recompensa Desbloqueada recientemente.
        /// Si es nula o vacía, no se ha desbloqueado una recompensa recientemente o ya se marcó como
        /// descartada en alguna ocasión anterior por el API o la misma WebApp.
        /// </summary>
        public RewardModel RecentlyUnlockedReward {
            get;
            set;
        }

        /// <summary>
        /// Tip del Día
        /// </summary>
        public TipModel TipOfTheDay {
            get;
            set;
        }

        public LayoutNotification[] Notifications {
            get;
            set;
        }
    }
}

Kms Cloud Web App/Controllers/OverviewController.cs
using Kms.Cloud.Database.Helpers;
using Kms.Cloud.WebApp.Models.Views;
using Kms.Cloud.Database;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kms.Cloud.WebApp.Controllers {
	[KmsAuthorize]
	public class OverviewController : BaseController {
		//
		// GET: /Overview/
		public ActionResult Index() {
			var modelValues = new OverviewValues();
			
			// > Obtener Tip del Día (último Tip)
			var lastTip = Database.UserTipHistoryStore.GetFirst(
				filter: f =>
					f.User.Guid == CurrentUser.Guid,
				orderBy: o =>
					o.OrderByDescending(b => b.CreationDate),
				include:
					new string[] { "Tip.TipCategory" }
			).Tip;

			modelValues.TipOfTheDay = new TipModel {
				Category = lastTip.TipCategory.GetGlobalization().Name,
				IconUri  = GetDynamicResourceUri(lastTip.TipCategory),
				Text     = lastTip.GetGlobalization().Text,
				TipId    = lastTip.Guid.ToBase64String()
			};
			
			// > Obtener registro de actividades del día de hoy
			var lowerBound = DateTime.UtcNow.Add(+ClientUtcOffset);
			lowerBound = new DateTime(
				lowerBound.Year, 
				lowerBound.Month, 
				lowerBound.Day,
				0,
				0,
				0,
				DateTimeKind.Utc
			).Add(-ClientUtcOffset);

			var lastDayData = Database.DataStore.GetAll(
				filter: f =>
					f.User.Guid == CurrentUser.Guid
					&& f.Timestamp <= DateTime.UtcNow
					&& f.Timestamp >= lowerBound,
				orderBy: o =>
					o.OrderBy(b => b.Timestamp)
			).ToArray();

			// > Calcular Horas de Sueño
			//   [MUST REVIEW + OPTIMIZE]
			// Inicialización de variables temporales
			DateTime? tmpTimestamp = null;

			// Inicialización de variables de propiedades
			modelValues.TodayDistanceCentimeters = 0;
			modelValues.EquivalentCo2Grams       = 0;
			modelValues.TodaySleepTime           = new TimeSpan(0);

			foreach ( var data in lastDayData ) {
				if ( data.Activity == DataActivity.Sleep ) {
					// + Si no hay Timestamp inicial, establecerlo
					if ( ! tmpTimestamp.HasValue )
						tmpTimestamp = data.Timestamp;

					
				} else {
					// + Si hay Timestamp inicial se calcula la diferencia temporal,
					//   se añade al total de Horas de Sueño y se "blanquea" el
					//   Timestamp inicial
					if ( tmpTimestamp.HasValue ) {
						modelValues.TodaySleepTime = modelValues.TodaySleepTime.Add(
							data.Timestamp - tmpTimestamp.Value
						);

						tmpTimestamp = null;
					}

					// + Sumar valores de otras propiedades
					modelValues.TodayDistanceCentimeters += data.Steps * data.StrideLength;
					modelValues.EquivalentCo2Grams       += data.EqualsCo2;
					modelValues.EquivalentKcalRaw        += data.EqualsKcal;
					modelValues.EquivalentCashRaw        += data.EqualsCash;
				}
			}

			// > Establecer Tip del Día
			modelValues.TipOfTheDay = this.LayoutValues.TipOfTheDay;

			// > Establecer fecha de última sincronización
		    var lastData = Database.DataStore.GetFirst(
		        filter: f =>
		            f.User.Guid == CurrentUser.Guid,
		        orderBy: o =>
		            o.OrderByDescending(b => b.CreationDate)
		    );

		    modelValues.LastSyncDateTime = lastData == null
		        ? default(DateTime)
		        : lastData.CreationDate.Add(+ClientUtcOffset);

			// > Devolver la vista
			return View(modelValues);
		}
	}
}

Kms Cloud Web App/Views/Shared/_Layout.cshtml
@{ LayoutValues layoutValues = (LayoutValues)ViewBag.Layout; }

<!DOCTYPE html>
<html lang="@CultureInfo.CurrentCulture.TwoLetterISOLanguageName.ToLower()" data-culture-code="@CultureInfo.CurrentCulture.Name">
<head>
	<meta charset="utf-8" />
	<meta name="description" content="The description of my page" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	@* user-scalable=no << Eliminado de {viewport} cuz' then it's not responsive *@
	
	<title>KMS@(String.IsNullOrEmpty(ViewBag.Title) ? "" : " :: " + ViewBag.Title)</title>

	@* Styles *@
	@Html.RenderCssBundle("~/Assets/Stylesheets.css.bundle", BundleOptions.Combined)
	@* Scripts *@
	@Html.RenderJsBundle("~/Assets/Javascript.js.bundle", BundleOptions.Combined)
</head>
<body data-distance-unit="@(RegionInfo.CurrentRegion.IsMetric ? "kms" : "mi")" data-weight-unit="@(RegionInfo.CurrentRegion.IsMetric ? "kg" : "lb")" data-ajax-cache="@layoutValues.AjaxCache" data-user-signup="@layoutValues.UserSignup">
	<header>
		<div class="contenedor2">
			<a href="@Url.Action("Index", "Overview", new { lang = CultureInfo.CurrentCulture.Name })">
				<h1>
					<span class="ocultar">KMS</span>
					<img src="~/Images/Header/Header.KmsLogo.png" alt="KMS">
				</h1>
			</a>
			<nav>
				<ul>
					<li>
						@Html.ActionLink(
							LayoutStrings.MyProfile,
							"Index",
							"Overview",
							null,
							new {
								@class = layoutValues.Section == LayoutValues.MainSection.MyProfile ? "active" : ""
							}
						)
					</li>
					<li>
						@Html.ActionLink(
							LayoutStrings.Tips,
							"Index",
							"Tips",
							null,
							new {
								@class = layoutValues.Section == LayoutValues.MainSection.Tips ? "active" : ""
							}
						)
					</li>
					<li>
						@Html.ActionLink(
							LayoutStrings.Rewards,
							"Index",
							"Rewards",
							null,
							new {
								@class = layoutValues.Section == LayoutValues.MainSection.Rewards ? "active" : ""
							}
						)
					</li>
					<li>
						@Html.ActionLink(
							LayoutStrings.Logout,
							"Logout",
							"Login"
						)
					</li>
				</ul>
			</nav>
		</div>
	</header>

	<div id="wrap">
		@* -- Left Sidebar --- *@
		<aside id="sidebar" style="visibility:collapse;opacity:0">
		@* - Datos generales del Usuario - *@
			<section id="Usuario">
				<h2>@layoutValues.UserName @layoutValues.UserLastname</h2>
				<figure>
					<img onclick="setKMS_userPicture()" src="@layoutValues.UserPicture.AbsoluteUri">
				</figure>
				<span class="distancia">
					@layoutValues.TotalDistance @(RegionInfo.CurrentRegion.IsMetric ? "kms" : "mi")
				</span>
				<span class="origen">
					@layoutValues.LocationString.ToUpper()
				</span>
				@using ( Html.BeginForm("UploadPicture", "Account", FormMethod.Post, new { enctype = "multipart/form-data" }) ) {
					<input type="file" name="file" />
				}
			</section>

			@* - Próxima Recompensa (o última recompensa ganada) - *@
			<section id="recompensaDash">
				<div id="recompensaDashReciente" style="@(layoutValues.RecentlyUnlockedReward.Discarded ? "display:none" : "")" data-discarded="@(layoutValues.RecentlyUnlockedReward.Discarded ? "1" : "0")" data-id="@layoutValues.RecentlyUnlockedReward.RewardId">
					<img src="@layoutValues.RecentlyUnlockedReward.IconUri" alt="@layoutValues.RecentlyUnlockedReward.Title">
				    <h3>@layoutValues.RecentlyUnlockedReward.Title</h3>
				    <article>
				        @layoutValues.RecentlyUnlockedReward.Text
				    </article>
					<a href="#" class="botonDorado">@LayoutStrings.ViewNextReward.ToUpper()</a>
				</div>    

				<div id="recompensaDashSiguiente" style="@(layoutValues.RecentlyUnlockedReward.Discarded ? "" : "display:none")">
					<span class="proxRecomp">@LayoutStrings.NextRewardIn.ToUpper(CultureInfo.CurrentCulture)</span>
					<span class="bandera">
						<img src="~/Images/Sidebar/Sidebar.Medal.gif" alt="">
					</span>
					<span class="kms">
						@layoutValues.NextRewardsDistanceRemaining @(RegionInfo.CurrentRegion.IsMetric ? "kms" : "mi")
					</span>
					<div id="barra">
						<div class="progreso" style="width:@((layoutValues.TotalDistanceCentimeters / layoutValues.NextRewardDistanceCentimeters) * 100)%;"></div>
					</div>
					<a href="#" class="botonDorado">@LayoutStrings.ViewLastReward.ToUpper()</a>
				</div>
			</section>

			<section id="tipDelDia">
				<figure>
					<img src="@layoutValues.TipOfTheDay.IconUri.AbsoluteUri" alt="@layoutValues.TipOfTheDay.Category">
				</figure>
				<h3>@LayoutStrings.TipOfTheDay.ToUpper()</h3>
				<article>
					@layoutValues.TipOfTheDay.Text
				</article>
			</section>

			<section id="redes-sidebar">
				<ul>
					<li><a href="#" class="corona"></a></li>
					<li><a href="#" class="facebook"></a></li>
					<li><a href="#" class="twitter"></a></li>
				</ul>
			</section>
		</aside>

		@* -- Body -- *@
		<section id="contenidos">
			@RenderBody()
			<div class="bottom-abajo"></div>
		</section>

		<div style="clear:both"></div>
	</div>

	<footer>
		<div class="contenedor">
			@*<nav>
				<ul>
					<li>
						@Html.ActionLink(
							LayoutStrings.FooterProduct,
							"Index",
							"Entry"
						)
					</li>
					<li>
						@Html.ActionLink(
							LayoutStrings.FooterServices,
							"Index",
							"Entry"
						)
					</li>
					<li>
						@Html.ActionLink(
							LayoutStrings.FooterStores,
							"Index",
							"Entry"
						)
					</li>
					<li>
						@Html.ActionLink(
							LayoutStrings.FooterUs,
							"Index",
							"Entry"
						)
					</li>
					<li>
						@Html.ActionLink(
							LayoutStrings.FooterKms,
							"Index",
							"Entry"
						)
					</li>
				</ul>
			</nav>*@
			<ul class="redes">
				<li>
					<a href="https://www.facebook.com/Kms.mex" target="_blank">
						<img src="~/Images/Footer/Footer.Facebook.png" alt="Facebook: KMS.mex">
					</a>
				</li>
				<li>
					<a href="https://twitter.com/kmsmex" target="_blank">
						<img src="~/Images/Footer/Footer.Twitter.png" alt="Twitter: &#64;kmsmex">
					</a>
				</li>
				<li>
					@* TODO: Establecer {subject} y {body} a texto predefinido *@
					<a href="mailto:dime@kms.me" target="_blank">
						<img src="~/Images/Footer/Footer.Mail.png" alt="Email: dime&#64;kms.me">
					</a>
				</li>
			</ul>
		</div>
	</footer>

	@* Footer Scripts (Optional) *@
	@RenderSection("FooterScripts", required: false)
</body>
</html>